### ISSUE TITLE
wave header contains wrong data

### ISSUE THREAD

**Issue by gitymon** [mbitsnbites/soundbox#1]
I got some weird misalignment when using audio.currentTime

i believe it was caused by:
   var l1 = waveWords \* 2 - 8; 
   https://github.com/mbitsnbites/soundbox/blob/master/player.js#L67

i fixed it in my code by using
   var l1 = waveWords \* 2 + 44 - 8; 
so basicly: included the header itself in the chunksize

**Comment by mbitsnbites** [comment]
Thanks! It was obviously an oversight. Fixed in 41b1342831917f217d32b581e5d03852aad3e469
