### ISSUE TITLE
Locally on Safari: Unexpected error: The operation is insecure.

### ISSUE THREAD

**Issue by esaruoho** [mbitsnbites/soundbox#10]
I tried to run soundbox locally on Safari 11 (I'm on macOS High Sierra (OS X 10.13)) and got "Unexpected error: The operation is insecure." -alert popup error.

<img width="478" alt="screen shot 2017-10-04 at 11 00 34" src="https://user-images.githubusercontent.com/4966687/31165317-454b538c-a8f3-11e7-9a6d-1c3ff6d0e34d.png">

**Comment by mbitsnbites** [comment]
There are currently no plans to support local (file://) execution of SoundBox. Rather, I'm considering adding server/client functionality that will make local execution impossible.

For macOS, consider something like: https://lifehacker.com/start-a-simple-web-server-from-any-directory-on-your-ma-496425450
