### ISSUE TITLE
Delay probably not working as intended (sometimes)

### ISSUE THREAD

**Issue by vsariola** [mbitsnbites/soundbox#11]
**Problem**: The comments indicate that the right channel delay should appear in left channel and vice versa (right->left, left->right). However, if song.rowLen is an odd number and delay time is an odd integer, left channel feeds left and right channel feeds right (left->left, right->right).

**Cause**: In the player-small.js, dly is computed as "dly = instr.i[27] * rowLen" and the delay for the left channel is computed by  lsample += chnBuf[k-dly+1]. Odd numbered channels are right channel, k is always an even number. If dly is an odd number, the left channel feeds the left channel.

**Steps to reproduce**: In the editor, put panning to slow (but not zero) and panning amount to maximum. Use bpm which results in an odd rowLen (120 is fine) and write out few patterns with only one note. Adjust the delay time slider to an odd number and give significant delay e.g. 75%. Observe the VU-meters.

**Possible solutions**: 
1. round dly to nearest even number. left->right and right->left delay will always result.
2. round rowLen to an even number. BPM might be a little off.
3. round rowLen to an odd number and make this "a feature", so the user can use even delays to have right->left left->right delay, and odd delays to have right->right and left->left delay. I don't recommend this because it is quite unintuitive behaviour to the user.

**Comment by mbitsnbites** [comment]
Excellent bug report! :heart:

I will probably go with something like your suggested solution 1.

B.t.w. the player routine is implemented in three places: `player-small.js` (for demos etc), `player-worker.js` (used by the editor) and `jammer.js` (used for real-time sound generation). This bug seems to be present in `player-worker.js` and `player-small.js`.
