### ISSUE TITLE
suggestion: implement < and > for raising/lowering octave of keyboard

### ISSUE THREAD

**Issue by esaruoho** [mbitsnbites/soundbox#12]
It'd be absolutely awesome if we could use < and > (left of the z-key on most keyboard) to raise or lower the octave of the keyboard.

**Comment by mbitsnbites** [comment]
Good suggestion! It would be nice if could adhere to some sort of standard in music/tracker software. Do you know of any examples of what other music editors use to shift octaves?

**Comment by esaruoho** [comment]
@mbitsnbites most old dos trackers etc would use / and * on the numpad to switch octaves, and since numpad isn't everywhere, < and > are used to switch.

screamtracker3, impulsetracker2, fasttracker2, schismtracker, buzztracker, renoise, modplugtracker openmpt etc. is this okay?
