### ISSUE TITLE
Can I use the player on a website?

### ISSUE THREAD

**Issue by nicollet** [mbitsnbites/soundbox#2]
Hi,

I'd like to use soundbox player on a website to add some music.
Can I just do that? Is this permitted by the license, without the GPL being viral to the whole website?

Thank you for your help.
And by the way, it's amazing what you have done, congratz!

**Comment by mbitsnbites** [comment]
You can use the player routine, which is released under a more permissive licence: https://github.com/mbitsnbites/soundbox/blob/master/player-small.js

See http://sb.bitsnbites.eu/demo.html for an example of how to use it.
