### ISSUE TITLE
Too easy to destroy your instrument settings accidentally

### ISSUE THREAD

**Issue by vsariola** [mbitsnbites/soundbox#24]
**Problem**: The user has accidentally the instrument preset selected when trying to input notes on the keyboard. If any preset starts with the letter you press, all your instrument settings are overwritten.

**Possible solution**: Disable keyboard in the select-tag, as per https://stackoverflow.com/questions/1227146/disable-keyboard-in-html-select-tag

**Comment by noxarivis** [comment]
i thought about makeing it possible to export the settings as base64 to share and save instruments

**Comment by mbitsnbites** [comment]
Disabling the keyboard sounds like a good solution.

Import and export for instruments is also a good idea, and something that is missing. For consistency, the instrument data should work like the song data: I.e. a versioned binary blob with import/export functions.

**Comment by esaruoho** [comment]
it's good to disable keyboard input in the presets.

what's even better, would be to wrap Tab in such a way that the first Tab selects "pattern order editor", second Tab-press selects "note editor" and third tab-press selects "parameter change editor". then the next tab would re-select "pattern order editor".

simple and makes sense.
