### ISSUE TITLE
Can't run locally on Chrome (file://), a possible fix

### ISSUE THREAD

**Issue by bryc** [mbitsnbites/soundbox#3]
When opening index.html locally on Chrome I get this error:

> Unexpected error: Failed to construct 'Worker': Script at 'file:///R:/GitHub/soundbox-master/player-worker.js' cannot be accessed from origin 'null'.

This is because of cross-origin policies that affect retrieval of external files. Just like XHR, Workers being able to access files in the current working directory is considered a security issue. Firefox doesn't have this issue.

A suggestion: wrap the worker code in a function, load it, and feed the Worker a Blob URI of the function body:
### **player-worker.js:**
```js
function CPlayerWorker() {
    // all worker code here
}
```
### **gui.js:**
```js
// must load the script into global scope (or anywhere else accessible in player.js)
include("player-worker.js");
```
### **player.js:**
```js
// CPlayerWorker is the Worker wrapper, so turn it into a Blob and load it:
var mWorker = new Worker(URL.createObjectURL(new Blob(["("+CPlayerWorker+")()"])));
// this might be more robust:
var mWorker = new Worker(URL.createObjectURL(new Blob(["("+CPlayerWorker.toString()+")()"])));
// you can avoid using IIFE by extracting the function body itself (between first { and last }):
var mWorker = new Worker(URL.createObjectURL(new Blob([CPlayerWorker.toString().replace(/(^.*?\{|\}$)/g,"")])));
```

This is just an idea. Of course, if you don't wish to support running SoundBox via file:// (since it is primarily a hosted-app), it is at least nice to know how it behaves under another environment. :~)

**Comment by bryc** [comment]
Also ... it would be nice to be able to loop or replay without having to buffer the entire song again. And tracker-style loop points to start again after an intro, etc.  Cheers

**Comment by mbitsnbites** [comment]
Thanks for the effort and detailed solution! However, there are currently no plans to add support for local execution. See #10 

On the bright side, I've added support for looping playback. ;-)
