### ISSUE TITLE
suggestion: dynamic song file size display in interface

### ISSUE THREAD

**Issue by esaruoho** [mbitsnbites/soundbox#32]
It'd be great to be able to see what size the song currently is - this would really help with the optimization process. I don't know if a song saved at 471bytes is like super-ultra-drastic-large, and thus i'm not sure what i could do to optimize it - i'd like to be able to figure out if using the alphabet for patterns takes more size than numbers, and if you have pattern numbers 0, 2, 5, 9 in use, instead of 0,1,2,3 - will they take more space, etc. to constantly see what the song file size is, would really help.

especially when trying to suss out how many channels can be used in a 4kb intro before everything goes wrong.

**Comment by mbitsnbites** [comment]
Good suggestion. One alternative could be to dummy-export the tune at regular intervals an display the figure somewhere, but that may have unwanted side effects (choppy sound, outdated size figure). Perhaps an explicit "calc size" action is better.

Also keep in mind: no song representation is equal to a final product (closure compiler, inlined player routine, pngout, ...).

**Comment by esaruoho** [comment]
definitely, a button that toggles calc size is a better solution than dynamic dummyexporting which might reduce app responsiveness.
