### ISSUE TITLE
Let users choose the count of the channels from 2 to 32 or higher.

### ISSUE THREAD

**Issue by noxarivis** [mbitsnbites/soundbox#5]
8 channels (instruments) are not enouth for me, i wish for an option to change the count of it like i can change the count of the rows per pattern

**Comment by mbitsnbites** [comment]
I'm currently working on a fix that will add support for "many" channels. There will still be a fixed max (which can potentially be quite high), but the exported song data will only contain the actually used channels.

**Comment by mbitsnbites** [comment]
The song format and player engine now supports up to 256 channels/instruments, but the UI is currently limited to 16 channels (mostly a design issue, but it's easy to update if needed).

**Comment by noxarivis** [comment]
i am fine with just a horizontal scroll bar
