### ISSUE TITLE
Let users choose the length of the song.

### ISSUE THREAD

**Issue by noxarivis** [mbitsnbites/soundbox#6]
I'd like to extend the length because i try to produce speedcore music, it needs a high BPM and a longer sequencer table.
(related to the wider sequencer table (more channels))

**Comment by mbitsnbites** [comment]
The reason that the length and number of channels is fixed is to simplify the player routine logic. I think that enabling longer tunes may be trivial (iirc), so will look into it.

**Comment by mbitsnbites** [comment]
WoWorking on a fix.

**Comment by mbitsnbites** [comment]
Now the UI has been updated to 500 song lines (the song format supports up to 65535 lines, so the UI could be updated in the future).

**Comment by noxarivis** [comment]
top :)
