### ISSUE TITLE
Proposal to improve kick synthesis and save some bytes in player.js

### ISSUE THREAD

**Issue by vsariola** [mbitsnbites/soundbox#70]
I've been doing some research into improving the kicks, which do not have enough snap and oomph to my taste. The core reason seems to be that the pitch drop using o1xenv/o2xenv simply isn't fast enough: the pitch frequency is ~ envelope^2. I found much better kicks by having steeper drops i.e. for example pitch frequency ~ envelope^4 or even envelope^6.

I came up with a solution that allows this in a backward compatible manner and saves bytes in the process: instead of having "o1xenv" and "o2xenv" as binary toggles, make them continuosly changing (for example: we could have "o1xenv = instr.i[3] / 4" and similarly for the o2xenv).

Then, in the player, one would change the following lines:
```
t = o1t;
if (o1xenv) {
   t *= e * e;
}
c1 += t;
```
into this:
```
c1 += o1t * e ** o1xenv;
```
The exponentiation operator is ES7 stuff, but for older browsers, this can be done with slightly more bytes:
```
c1 += o1t * Math.pow(e,o1xenv);
```
Note that this is exactly the same as old behaviour when o1xenv = 0, even for the case e = 0 (0 ** 0 = 1).

What are the benefits?
1. Uncompressed song data size does not change, as the old behavior can be achieved by setting instr.i[3] as 8.
2. Assuming minification uses single letter variables, the old code is 22 characters per oscillator. In ES7, player.js is 12 characters per oscillator ("/4" taken into account), : a gain of 20 characters for two oscillators. Version for ES6 and older is 21 characters: a gain of 2 characters for two oscillators.
3. Might be useful to make funky / brass sounds with instr.i[3] = 1 or 2 i.e. when the note is release, the pitch starts to slightly drop and then drops very steeply in the end.
4. But most importantly, more snap and oomph to kicks!

So, to me it looks like a nobrainer, but I did not actually test it in Soundbox (I just tested the kick synthesis elsewhere). There might be performance issues: I assume Math.pow is slightly slower than e*e. Also, this would require slightly different binary song instrument data so we would have to bump up the binary data version.

Note that I proposed using a divisor of 4 to guarantee that the uncompressed song data size does not change for current songs. But 8 or 16 would allow more granularity, and I have not really sound wise explored what could be done with small exponents. I believe exponents beyond 10 are unnecessary, but this should also be tested by playing around with the sounds. Someone with a "professional ear" might be needed.

**Comment by mbitsnbites** [comment]
This sounds like a good solution. Will check. Actually toyed with s similar solution yesterday.

I'd like to fix decay too in a similar way since most instruments would benefit from a more exponential envelope falloff.

**Comment by vsariola** [comment]
I think kicks would benefit from exponents less than one in the envelope i.e. the envelope be raised to the power of 1/2 or 1/4. This would allow the kick to maintain roughly equal levels for the duration of decay, and the volume would only fade out in the end of the kick. But something similar can currently be achieved using distortion, so this is not that critical.

So having an exponent for the envelope would be nice, but would require a new parameter and can be sort of done already, whereas o1xenv stuff is already there just to be repurposed.

**Comment by vsariola** [comment]
Well, I tested this already.

Here's the branch: https://github.com/vsariola/soundbox/tree/feature/xenv_change

What do you think Marcus?

**Comment by vsariola** [comment]
I just hit you with a PR to get your attention.
