### ISSUE TITLE
Song doesn't play on Chrome

### ISSUE THREAD

**Issue by vsariola** [mbitsnbites/soundbox#9]
Platform: Windows Chrome 61.0.3163.100.

Problem: The "(play) Song" button on the left does not work anymore. Steps to reproduce:

1. Start the software
2. Load any song
3. Hit "(play) Song" button on the left

I can see the channels active, but I don't hear any sound. This is a very new thing; I think the version on http://sb.bitsnbites.eu/ worked last week.

Play Range works fine, and I can hear the sounds when pressing buttons.

**Comment by vsariola** [comment]
Never mind, latest master seems to work again.

**Comment by mbitsnbites** [comment]
Thanks for the report. I did a few edits a couple of days ago, fixing playback for iOS/Safari and Android/Chrome, so you might have gotten an intermediate state.

Also, I often have problems with the server/browser caches, e.g. reloading the html but not the js. Annoying.
